<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111124063306 extends AbstractMigration {

    public function up(Schema $schema) {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");              
        
        $sql = file_get_contents('sql/init.data.sql',FILE_USE_INCLUDE_PATH);
        $this->addSql($sql);
    }

    public function down(Schema $schema) {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $this->addSql("DROP TABLE IF EXISTS courses_instructors, offerings, courses, streams,  instructors");
    }

}
