<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Adding a column for length of the course in weeks
 */
class Version20111205030316 extends AbstractMigration {

    public function up(Schema $schema) {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE offerings ADD COLUMN length INT NULL");
    }

    public function down(Schema $schema) {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE offerings DROP COLUMN length");
    }

}
